// ignore_for_file: non_constant_identifier_names
import 'package:flutter/material.dart';

class AppColor {
  static const Color primaryColor = Color(0xffFFC000); // Yellow from the header and accents
  static const Color primaryBackgroundColor = Color(0xffFFFFFF); // White background
  static const Color loginButtonColor = Color(0xffE93C3C); // Red for primary buttons
  static const Color fontColor = Color(0xff1F1F39); // Dark gray/black for most text
  static const Color dividerColor = Color(0xffF0F0F0); // Light gray for dividers
  static const Color textSignupColor = Color(0xff6E7191); // Gray for secondary text
  static const Color addNewBtnColor = Color(0xffE93C3C); // Red for "add new" type buttons/accents
  static const Color myAddrBgColor = Color(0xffF7F7FC); // Light background for address sections
  static const Color homeIconColor = Color(0xffE93C3C); // Red for active home icon
  static const Color activeTxtColor = Color(0xffE93C3C); // Red for active text elements
  static const Color activeTxtBorderColor = Color(0xffFFC000); // Yellow for active borders/highlights
  static const Color deleveryColor = Color(0xffFFEDF4); // Light pink/red for delivery status backgrounds
  static const Color redColor = Color(0xffE93C3C); // Consistent red
  static const Color deleteBtnColor = Color(0xffE93C3C); // Consistent red for delete actions
  static const Color searchBarbg = Color(0xffF7F7FC); // Light gray for search bar background
  static const Color viewAllbg = Color(0xffFFEDF4); // Light pink/red for "View All" button background
  static const Color itembg = Color(0xffFFFFFF); // White for individual item backgrounds
  static const Color delivaryActive = Color(0xffE93C3C); // Red for active delivery status
  static const Color delivaryInactive = Color(0xffBDEFFF); // Blue for inactive delivery status (from original, no clear inactive in UI)
  static const Color green = Color(0xff1AB759); // Green (from original, not prominent in UI)
  static const Color yellow = Color(0xffFFC000); // Consistent yellow
  static const Color gray = Color(0xff6E7191); // Consistent gray
  static const Color bgColor = Color(0xffF7F7FC); // General light background color
  static const Color darkGray = Color(0xff1F1F39); // Consistent dark gray
  static const Color blueTransparent = Color(0xffD6F5FF); // Light blue (from original, not prominent in UI)
  static const Color blueTextColor = Color(0xff00749B); // Blue text (from original, not prominent in UI)
  static const Color warning = Color(0xffF6A609); // Orange for warnings
  static const Color success = Color(0xff2AC769); // Green for success
  static const Color error = Color(0xffFB4E4E); // Red for errors
  static const Color pending = Color(0xffFFEEC6); // Light yellow for pending status background
  static const Color pendingText = Color(0xffF6A609); // Orange for pending status text
  static const Color preparing = Color(0xffE1FFED); // Light green for preparing status background
  static const Color preparingText = Color(0xff2AC769); // Green for preparing status text
  static const Color ontheway = Color(0xffBDEFFF); // Light blue for "on the way" status (from original)
  static const Color delivered = Color(0xffFFD7E7); // Light pink for delivered status (from original)
  static const Color canceled = Color(0xffFFDADA); // Light red for canceled status background
  static const Color canceledText = Color(0xffFB4E4E); // Red for canceled status text

  static const Color shadow = Color(0x337E858E); // Adjusted shadow for subtle effect
}



class Images {
  static String get logo => 'assets/images/logo.png';
  static String get appLogo => 'assets/images/app_logo.png';
  static String get splashLogo => 'assets/images/splash_logo.png';

  static String get change_language => 'assets/icons/change_language.svg';
  static String get terms_condition => 'assets/icons/terms_condition.svg';
  static String get privacy => 'assets/icons/privacy.svg';
  static String get calling => 'assets/icons/calling.svg';
  static String get about_us => 'assets/icons/about_us.svg';
  static String get homee => 'assets/icons/home.svg';
  static String get home => 'assets/images/home.png';
  static String get menu => 'assets/images/menu.png';
  static String get offer => 'assets/images/offer.png';
  static String get cart => 'assets/images/cart.png';
  static String get cartHasItem => 'assets/images/cartHasItem.png';
  static String get profile_circle => 'assets/images/profile_circle.png';
  static String get back => 'assets/icons/back.svg';
  static String get profile => 'assets/images/profile.png';
  static String get dotCircle => 'assets/images/dot_circle.png';
  static String get order => 'assets/icons/order.svg';
  static String get chat => 'assets/icons/chat.svg';
  static String get other => 'assets/icons/other.svg';
  static String get work => 'assets/icons/work.svg';
  static String get address => 'assets/icons/address.svg';
  static String get edit => 'assets/icons/edit.svg';
  static String get change_pass => 'assets/icons/change_pass.svg';
  static String get logout => 'assets/icons/logout.svg';
  static String get tick => 'assets/icons/tick-circle.svg';
  static String get roundStepper => 'assets/icons/round_stepper.svg';
  static String get flagEn => 'assets/images/en.png';
  static String get flagDe => 'assets/images/de.png';
  static String get flagBd => 'assets/images/bd.png';
  static String get flagAr => 'assets/images/ar.png';
  static String get flagFr => 'assets/images/fr.png';
  static String get iconHome => 'assets/icons/home.svg';
  static String get iconMenu => 'assets/icons/menu.svg';
  static String get iconOffers => 'assets/icons/offers.svg';
  static String get iconProfile => 'assets/icons/profile-circle.svg';
  static String get iconArrowDown => 'assets/icons/arrow_down.svg';
  static String get demo => 'assets/images/demo.jpeg';
  static String get closeCircle => 'assets/images/close_circle.png';
  static String get item1 => 'assets/images/item1.png';
  static String get iconCart => 'assets/icons/bag.svg';
  static String get iconDetails => 'assets/icons/detailsIcon.svg';
  static String get shop => 'assets/icons/shop.svg';
  static String get person => 'assets/icons/person.svg';
  static String get gallery => 'assets/icons/gallery.svg';
  static String get right_arrow => 'assets/icons/right_arrow.svg';
  static String get round_arrow => 'assets/icons/round_arrow.svg';
  static String get dot_icon => 'assets/icons/dot_icon.svg';
  static String get send => 'assets/icons/send.svg';
  static String get iconRowVertical => 'assets/icons/row-vertical.svg';
  static String get iconListView => 'assets/icons/list_icon.svg';
  static String get iconGridView => 'assets/icons/grid_icon.svg';
  static String get iconSearch => 'assets/icons/icon_search.svg';
  static String get nonVeg => 'assets/images/non_veg.png';
  static String get veg => 'assets/images/veg.png';
  static String get IconClose => 'assets/icons/close-circle.svg';
  static String get active_order => 'assets/icons/active_order.svg';
  static String get deactive => 'assets/icons/deactive.svg';
  static String get IconAddItem => 'assets/icons/add-circle.svg';
  static String get IconRemoveItem => 'assets/images/remove.png';
  static String get offer3 => 'assets/images/offer3.png';
  static String get offer4 => 'assets/images/offer4.png';
  static String get IconVariation => 'assets/icons/circle.svg';
  static String get IconVariationSelected => 'assets/icons/selected_circle.svg';
  static String get iconTickedNo => 'assets/icons/ticked-no-square.svg';
  static String get iconTickedYes => 'assets/icons/ticked-yes-square.svg';
  static String get message => 'assets/icons/messages.svg';
  static String get call => 'assets/icons/call.svg';
  static String get mapView => 'assets/images/map.png';
  static String get mapViewLarge => 'assets/images/mapLarge.png';
  static String get homeIcon => 'assets/icons/home_icon.svg';
  static String get locationIcon => 'assets/icons/location_icon.svg';
  static String get officeIcon => 'assets/icons/office_icon.svg';
  static String get sms_tracking => 'assets/icons/sms-tracking.svg';
  static String get cll_center => 'assets/icons/call-center.svg';
  static String get thik => 'assets/icons/thik.svg';
  static String get iconCard => 'assets/icons/card.svg';
  static String get iconCod => 'assets/icons/cod.svg';
  static String get iconPromo => 'assets/icons/promo_icon.svg';
  static String get iconArrowRight => 'assets/icons/arrow-right.svg';
  static String get iconRouting => 'assets/icons/routing_icon.svg';
  static String get iconTimeline => 'assets/icons/timeline.svg';
  static String get iconTrash => 'assets/icons/trash.svg';
  static String get iconEditProfile => 'assets/icons/edit_profile.svg';
  static String get emptyCart => 'assets/images/empty_cart.png';
  static String get lostConnection => 'assets/images/lost_connection.png';
  static String get searchNotFound => 'assets/images/search_not_found.png';
  static String get marker => 'assets/images/marker_user.png';
  static String get markerBranch => 'assets/images/marker_branch.png';
  // static String get markerBranch => 'assets/icons/marker_branch.svg';
  static String get iconAdd => 'assets/icons/add_icon.svg';
  static String get iconEdit => 'assets/icons/edit_icon.svg';
  static String get iconBranch => 'assets/icons/branch.svg';
  static String get animationConfirmed => 'assets/animation/confirmed.json';
  static String get paymentLogo => 'assets/icons/payment_logo.svg';
  static String get iconPaypal => 'assets/icons/paypal.svg';
  static String get animationProcessing => 'assets/animation/processing.json';
  static String get animationPreparing => 'assets/animation/preparing.json';
  static String get animationDelivered => 'assets/animation/delivered.json';
  static String get locationService => 'assets/icons/location_service.svg';
  static String get iconMap => 'assets/icons/map_icon.svg';
  static String get prepared => 'assets/animation/prepared.gif';
}
